name:                egsParser
version:             0.1.0.0
github:              "mxxo/egsParser"
license:             BSD3
author:              "Max Orok"
maintainer:          "morok028@uottawa.ca"
copyright:           "2019 Max Orok"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mxxo/egsParser#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- scientific
- text

library:
  source-dirs: src

executables:
  egsParser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - egsParser

tests:
  egsParser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - egsParser
